FORMAT: 1A
HOST: https://orgmanager.miguelpiedrafita.com/api

# Orgmanager API

The Orgmanager API allows you to integrate Orgmanager with other applications and projects.

## Getting your token

To get your API token, go to the developers page of your orgmanager installation (http://orgmanager-installation.com/developers)

## User Data [/user]

### Get user info [GET]

+ Request
    + Headers
            Content-Type: application/json
            Accept: application/json
            Authorization: bearer {token}

+ Response 200 (application/json)

        {
            "id":1,
            "name":"Miguel Piedrafita",
            "email":"soy@miguelpiedrafita.com",
            "github_username":"m1guelpf",
            "created_at":"2017-01-25 18:44:32",
            "updated_at":"2017-02-16 19:40:50"
        }

## User Organizations [/user/orgs]

### Get user organizations [GET]

+ Request
    + Headers
            Content-Type: application/json
            Accept: application/json
            Authorization: bearer {token}

+ Response 200 (application/json)

        {
            "id":1,
            "name":"Test Organization",
            "url":"https:\/\/api.github.com\/orgs\/test-org",
            "description":null,
            "avatar":"https:\/\/miguelpiedrafita.com\/logo.png",
            "invitecount":100
        }

## Organizations [/org/{id}]

### Get organization info [GET]

+ Request
    + Headers
            Content-Type: application/json
            Accept: application/json
            Authorization: bearer {token}

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Test Org",
            "url": "https://api.github.com/orgs/test-org",
            "description": null,
            "avatar": "https://avatars.githubusercontent.com/1",
            "invitecount": 0
        }

### Change organization password [POST]

+ Request
    {
        "password": "{newpassword}"
    }

    + Headers
            Content-Type: application/json
            Accept: application/json
            Authorization: bearer {token}

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Test Org",
            "url": "https://api.github.com/orgs/test-org",
            "description": null,
            "avatar": "https://avatars.githubusercontent.com/1",
            "invitecount": 0,
            "password": "{newpassword}"
        }

### Update organization [PUT]

+ Request
    + Headers
            Content-Type: application/json
            Accept: application/json
            Authorization: bearer {token}

+ Response 204 (text/html; charset=UTF-8)

### Delete organization [DELETE]

+ Request
    + Headers
            Content-Type: application/json
            Accept: application/json
            Authorization: bearer {token}

+ Response 204 (text/html; charset=UTF-8)

## Join [/join/{id}]

### Join organization [POST]

+ Request
    {
        "username": "{github_username}"
    }

    + Headers
            Content-Type: application/json
            Accept: application/json
            Authorization: bearer {token}

+ Response 204 (text/html; charset=UTF-8)

## Stats [/stats]

### Get application stats [GET]

+ Request
    + Headers
            Content-Type: application/json
            Accept: application/json
            Authorization: bearer {token}

+ Response 200 (application/json)

        {
            "users": 10,
            "orgs": 4,
            "invites": 445
        }
